spring.application.name=repasse
server.port=${SRV_PORT:9595}
spring.datasource.url=${DATABASE_HOST:jdbc:mysql://localhost:3306/awrepasse?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:123456}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.flyway.locations=classpath:db/migration,classpath:db/testdata
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#habilita para nao aceitar propriedades que nao existe
spring.jackson.deserialization.fail-on-unknown-properties=true
#habilita para nao aceitar quando a opcao json-ingore esta em uso
spring.jackson.deserialization.fail-on-ignored-properties=true
spring.web.resources.add-mappings=false
server.servlet.context-path=/api

security.jwt.secret-key=3cfa76ef1493affe347c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000




spring.mail.host=mail.adeweb.com.br
spring.mail.port=465
spring.mail.username=repasse@adeweb.com.br
spring.mail.password=Ll4LY}~vK8JQ
spring.mail.properties.mail.protocol=smtp
spring.mail.properties.mail.tls=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=mail.adeweb.com.br


# SSL, post 465
spring.mail.properties.mail.smtp.socketFactory.port = 465
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory



pdf.directory=src/main